language: python

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker image build -t amenezes/$IMAGE_NAME:$IMAGE_TAG .
  - docker image push amenezes/$IMAGE_NAME:$IMAGE_TAG

env:
  global:
   - IMAGE_TAG=latest
   - IMAGE_NAME=python-unittest
