FROM python:3.6.8-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-dev \
                       sqlite \
                       gcc \
                       zlib-dev \
                       musl-dev \
                       make && \
    rm -rf /var/cache/apk/*

COPY requirements.txt .
COPY requirements-temas.txt .

RUN pip install -r requirements.txt
RUN pip install -r requirements-temas.txt
