version: '2'
services:
  python-unittest-textos:
    build:
      context: .
      dockerfile: Dockerfile.textos
  python-unittest-temas:
    build:
      context: .
      dockerfile: Dockerfile.temas
#    volumes:
#      - $PWD/textos:/app
#    command:
#      - python
#      - -m
#      - pytest
#      - -v
#      - tests/ocr_test.py
